---
- name: Install pip
  become: true
  yum:
    name: python-pip
    state: present

- name: Uninstall MariaDB
  become: true
  yum:
    name: mariadb*
    state: absent

- name: Install PyMySQL
  become: true
  pip:
    name: PyMySQL
    state: present

- name: Install RPM-GPG-KEY-mysql
  become: true
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  ignore_errors: true

- name: Install MySQL repository
  become: true
  yum:
    name: "https://repo.mysql.com//mysql84-community-release-el7-1.noarch.rpm"
    state: present

- name: Install MySQL packages
  become: true
  yum:
    name:
      - mysql-community-devel
      - mysql-community-server
      - mysql-community-client
    state: present
    
- name: Read CloudFormation outputs from file
  set_fact:
    cfn_outputs: "{{ lookup('file', 'cfn_outputs.json') | from_json }}"

- name: Parse DBEndpoint from CloudFormation outputs
  set_fact:
    db_endpoint: "{{ cfn_outputs | selectattr('OutputKey', 'equalto', 'DBEndpoint') | map(attribute='OutputValue') | first }}"

- name: Add database.yml.j2
  become: true
  template:
    src: templates/database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"
  vars:
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    db_endpoint: "{{ db_endpoint }}"

- name: Start MySQL service
  become: true
  systemd:
    name: mysqld
    state: started
  ignore_errors: true

- name: Use mysql_native_password
  community.mysql.mysql_user:
    name: admin
    host: "%"
    password: "{{ db_password }}"
    login_user: admin
    login_password: "{{ db_password }}"
    login_host: "{{ db_endpoint }}"
    priv: "*.*:ALL,GRANT"
    state: present
    plugin: mysql_native_password
  ignore_errors: true

- name: Restart MySQL service
  become: true
  systemd:
    name: mysqld
    state: restarted
