- name: yum update
  become: yes
  yum: 
    name: "*"
    state: latest

- name: install tools
  become: yes
  yum:
    name:
      - gcc-c++
      - openssl-devel
      - libyaml-devel
      - readline
      - readline-devel
      - zlib
      - zlib-devel
      - libffi-devel
      - libxml2 
      - libxslt 
      - libxml2-devel 
      - libxslt-devel 
      - sqlite-devel
      - ImageMagick
      - ImageMagick-devel
    state: present
    
# Gitのインストール
- name: Install git
  become: true
  yum:
    name: git
    state: present  # 入ってる状態にする
    lock_timeout: 60