---
- name: Create symlink for npm if not exists
  file:
    src: /usr/local/bin/npm
    dest: /usr/bin/npm
    state: link

- name: check yarn installed
  shell: yarn --version | grep {{ yarn_version }}
  register: check_yarn_installed
  changed_when: no
  ignore_errors: yes

- name: install yarn
  shell: npm install --global yarn@{{ yarn_version }}
  when: check_yarn_installed is failed
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:{{ ansible_env.PATH }}"
