---
- hosts: all
  become: yes
  become_method: sudo
  
  tasks:
    - name: Include 01-yum
      include_role:
        name: 01-yum

    - name: Include 02-ruby
      include_role:
        name: 02-ruby
        
    - name: Include 03-bundler
      include_role:
        name: 03-bundler
        
    - name: Include 04-rails
      include_role:
        name: 04-rails
        
    - name: Include 05-node
      include_role:
        name: 05-node
        
    - name: Include 06-mysql
      include_role:
        name: 06-mysql
        
    #- name: Include 07-deploy
      #include_role:
        #name: 07-deploy
  vars: 
    app_dir: /home/ec2-user/raisetech-live8-sample-app
    ansible_user: ec2-user
    aws_alb_host : "{{ (lookup('env','AWS_ALB_HOST')) }}"
    aws_db_pw : "{{ (lookup('env','AWS_DB_PW')) }}"
    aws_db_host : "{{ (lookup('env','AWS_DB_HOST')) }}"
    aws_s3_bucket: "{{ (lookup('env','AWS_S3_BUCKET')) }}"
    ansible_become_timeout: 30